version: "3"

services:
  websocket-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=8080
